config/routes.rb
Rails.application.routes.draw do
  resources :foodtrucks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'auth/:provider/callback', to: 'sessions#create'
get 'auth/failure', to: redirect('/') #where the user is redirected if they don't accept the requested permissions.
get 'home', to: 'home#show'
get 'me', to: 'me#show', as: 'me' #authenticated route that serves information specific to the current user
get 'signout', to: 'sessions#destroy', as: 'signout'
root to: "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foodtruck.rb
class Foodtruck < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
			user.email = auth.info.email
			user.picture = auth.info.image
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
  	redirect_to :login unless user_signed_in?
  end

private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
  	# converts current_user to a boolean by negating the negation
  	!!current_user
  end
end

app/controllers/foodtrucks_controller.rb
class FoodtrucksController < ApplicationController
  before_action :authenticate, :set_foodtruck, only: [:show, :edit, :update, :destroy]

  # GET /foodtrucks
  # GET /foodtrucks.json
  def index
    @foodtrucks = Foodtruck.all
  end

  # GET /foodtrucks/1
  # GET /foodtrucks/1.json
  def show
  end

  # GET /foodtrucks/new
  def new
    @foodtruck = Foodtruck.new
  end

  # GET /foodtrucks/1/edit
  def edit
  end

  # POST /foodtrucks
  # POST /foodtrucks.json
  def create
    @foodtruck = Foodtruck.new(foodtruck_params)

    respond_to do |format|
      if @foodtruck.save
        format.html { redirect_to @foodtruck, notice: 'Foodtruck was successfully created.' }
        format.json { render :show, status: :created, location: @foodtruck }
      else
        format.html { render :new }
        format.json { render json: @foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodtrucks/1
  # PATCH/PUT /foodtrucks/1.json
  def update
    respond_to do |format|
      if @foodtruck.update(foodtruck_params)
        format.html { redirect_to @foodtruck, notice: 'Foodtruck was successfully updated.' }
        format.json { render :show, status: :ok, location: @foodtruck }
      else
        format.html { render :edit }
        format.json { render json: @foodtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodtrucks/1
  # DELETE /foodtrucks/1.json
  def destroy
    @foodtruck.destroy
    respond_to do |format|
      format.html { redirect_to foodtrucks_url, notice: 'Foodtruck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodtruck
      @foodtruck = Foodtruck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foodtruck_params
      params.fetch(:foodtruck, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  	# @user = User.find_or_create_from_auth_hash(env["omniauth.auth"])
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])

  	session[:user_id] = @user.id
  	redirect_to :me
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodtrucks_helper.rb
module FoodtrucksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/views/foodtrucks/_form.html.erb
<%= form_with(model: foodtruck, local: true) do |form| %>
  <% if foodtruck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foodtruck.errors.count, "error") %> prohibited this foodtruck from being saved:</h2>

      <ul>
      <% foodtruck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foodtrucks/edit.html.erb
<h1>Editing Foodtruck</h1>

<%= render 'form', foodtruck: @foodtruck %>

<%= link_to 'Show', @foodtruck %> |
<%= link_to 'Back', foodtrucks_path %>

app/views/foodtrucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foodtrucks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foodtrucks.each do |foodtruck| %>
      <tr>
        <td><%= link_to 'Show', foodtruck %></td>
        <td><%= link_to 'Edit', edit_foodtruck_path(foodtruck) %></td>
        <td><%= link_to 'Destroy', foodtruck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foodtruck', new_foodtruck_path %>

app/views/foodtrucks/new.html.erb
<h1>New Foodtruck</h1>

<%= render 'form', foodtruck: @foodtruck %>

<%= link_to 'Back', foodtrucks_path %>

app/views/foodtrucks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_foodtruck_path(@foodtruck) %> |
<%= link_to 'Back', foodtrucks_path %>

app/views/home/show.html.erb
<!-- <h1> Welcome, please login to continue </h1>
<a href="/auth/google_oauth2">Sign in with Google</a> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunchapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
  Signed in as <%= current_user.first_name + ' ' + current_user.last_name %>!
  <%= link_to "Sign out", signout_path %>
</br>
<% else %>
<h1> Welcome, please login to continue </h1>
<%= link_to "Sign in with Google", "/auth/google_oauth2" %>
<% end %>

    <%= yield %>

  </body>
</html>

app/views/me/show.html.erb
<% if current_user %>
	<% current_user.attributes.each do |k, v| %>
		<b><%= k %>:</b> <%= v %> <br>
	<% end %>
<% end %>